.env
node_modules
.idea
data
stacks
tmp
/private

docker
.editorconfig
.eslintrc.cjs
.git
.gitignore
.github
README.md
CONTRIBUTING.md
SECURITY.md
LICENSE
compose.yaml
Dockerfile*

extra/close-incorrect-issue.js
extra/env2arg.js
extra/update-version.ts
extra/test-docker.ts
extra/reset-password.ts
extra/reformat-changelog.ts
extra/templates
